name: pyxis_mobile
description: Aura wallet project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #network
  dio: ^5.1.2
  retrofit: ^4.0.1

  #tools
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  #helper:
  permission_handler: ^10.2.0
  get_it: ^7.6.0
  intl: ^0.18.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.4

  #local db
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  flutter_secure_storage:
    git:
      path: flutter_secure_storage
      url: https://github.com/aura-nw/flutter_secure_storage.git
      ref: feature/biometric_mobile

  #state management:
  flutter_bloc: ^8.1.3

  #ui
  flutter_svg: ^2.0.7
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #aura_sdk:
  aura_wallet_core:
#    path: packages/aura-wallet-core
    git:
      url: https://github.com/aura-nw/aura-wallet-core.git
      ref: core_wallet
  aura_smart_account:
    path: ./packages/aura_smart_account

  #3-party
  share_plus: ^7.2.1
  web3auth_flutter: ^3.1.1

  #core
  data:
    path: cores/data
  domain:
    path: cores/domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  retrofit_generator: ^7.0.1
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  isar_generator: ^3.1.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter/Inter-VariableFont_slnt,wght.ttf
        - asset: assets/font/Inter/static/Inter-Black.ttf
        - asset: assets/font/Inter/static/Inter-Bold.ttf
        - asset: assets/font/Inter/static/Inter-ExtraBold.ttf
        - asset: assets/font/Inter/static/Inter-Light.ttf
        - asset: assets/font/Inter/static/Inter-Medium.ttf
        - asset: assets/font/Inter/static/Inter-Regular.ttf
        - asset: assets/font/Inter/static/Inter-SemiBold.ttf
        - asset: assets/font/Inter/static/Inter-Thin.ttf
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Black.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-BlackItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-BoldItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-ExtraBold.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-ExtraBoldItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-ExtraLight.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-ExtraLightItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Light.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-LightItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Medium.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-MediumItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-SemiBold.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-SemiBoldItalic.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-Thin.ttf
        - asset: assets/font/Be_Vietnam_Pro/BeVietnamPro-ThinItalic.ttf

